package com.test.sts.mybatis;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.ID
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.PWD
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.NAME
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.PHONE
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.EMAIL
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.PIC
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.DATE
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MODDATE
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    private Date moddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.FOLLOWER
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    private Integer follower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.FOLLOWING
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    private Integer following;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.BIRTH
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    private String birth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.ID
     *
     * @return the value of MEMBER.ID
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.ID
     *
     * @param id the value for MEMBER.ID
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.PWD
     *
     * @return the value of MEMBER.PWD
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.PWD
     *
     * @param pwd the value for MEMBER.PWD
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.NAME
     *
     * @return the value of MEMBER.NAME
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.NAME
     *
     * @param name the value for MEMBER.NAME
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.PHONE
     *
     * @return the value of MEMBER.PHONE
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.PHONE
     *
     * @param phone the value for MEMBER.PHONE
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.EMAIL
     *
     * @return the value of MEMBER.EMAIL
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.EMAIL
     *
     * @param email the value for MEMBER.EMAIL
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.PIC
     *
     * @return the value of MEMBER.PIC
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.PIC
     *
     * @param pic the value for MEMBER.PIC
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.DATE
     *
     * @return the value of MEMBER.DATE
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.DATE
     *
     * @param date the value for MEMBER.DATE
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MODDATE
     *
     * @return the value of MEMBER.MODDATE
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public Date getModdate() {
        return moddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MODDATE
     *
     * @param moddate the value for MEMBER.MODDATE
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public void setModdate(Date moddate) {
        this.moddate = moddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.FOLLOWER
     *
     * @return the value of MEMBER.FOLLOWER
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public Integer getFollower() {
        return follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.FOLLOWER
     *
     * @param follower the value for MEMBER.FOLLOWER
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public void setFollower(Integer follower) {
        this.follower = follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.FOLLOWING
     *
     * @return the value of MEMBER.FOLLOWING
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public Integer getFollowing() {
        return following;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.FOLLOWING
     *
     * @param following the value for MEMBER.FOLLOWING
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public void setFollowing(Integer following) {
        this.following = following;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.BIRTH
     *
     * @return the value of MEMBER.BIRTH
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.BIRTH
     *
     * @param birth the value for MEMBER.BIRTH
     *
     * @mbg.generated Thu Dec 20 10:42:29 KST 2018
     */
    public void setBirth(String birth) {
        this.birth = birth;
    }
}